<?= $this->doctype(); ?>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Interface NAO</title>
		<link rel="icon" type="image/png" href="/img/naoFavIcon.png" />
		<script type="text/javascript" src="<?= $this->baseUrl('/js/jquery.min.js');?>"></script>
		<script type="text/javascript" src="<?= $this->baseUrl('/js/jquery-ui.js');?>"></script>
		<link href="<?= $this->baseUrl('/css/style.css');?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?= $this->baseUrl('/bootstrap/css/bootstrap.css');?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?= $this->baseUrl('/bootstrap/css/bootstrap-responsive.css');?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?= $this->baseUrl('/css/jquery-ui.css');?>" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?= $this->baseUrl('js/jwplayer/jwplayer.js')?>"></script>
	</head>

	<body onload="attach_event_action_turn_left();attach_event_action_turn_right();attach_event_action_up(); attach_event_action_right(); attach_event_action_down(); attach_event_action_left();">
		

						<?= $this->layout()->content; ?>

		
		<script type="text/javascript" src="<?= $this->baseUrl('/bootstrap/js/bootstrap.js')?>"></script>
		<script type="text/javascript" src="<?= $this->baseUrl('/js/ajaxExecuteFile.js');?>"></script>
	</body>
</html>