<div class="row-fluid  content-heading title">
	<div class="span11 offset1">
		<h2>ColorPicker</h2>
	</div>
</div>
<div class="separator">
	<span></span>
</div>
   <!-- <div class="span6">
        <button class="btn btn-primary btn-danger margin  action" data-action="Rouge" data-active="false" onclick="attach_event_action(this);"><div class="center">Rouge</div></button>  
        <button class="btn btn-primary margin action" data-action="Bleu" data-active="false" onclick="attach_event_action(this);"><div class="center">Bleu</div></button>
        <button class="btn btn-success margin action" data-action="Vert" data-active="false" onclick="attach_event_action(this);"><div class="center">Vert</div></button>
        <button class="btn action margin " style="background: purple;" data-action="Violet" data-active="false" onclick="attach_event_action(this);"><div class="center">Violet</div></button>
        <button class="btn action margin " style="background: orange;" data-action="Orange" data-active="false" onclick="attach_event_action(this);"><div class="center">Orange</div></button>
        <button class="btn action margin " style="background: yellow;"data-action="Jaune" data-active="false" onclick="attach_event_action(this);"><div class="center">Jaune</div></button>
    </div>-->
</div>

<div class="span6">
<button class="btn btn-primary btn-large margin large action" data-action="NaoStory" data-active="false" onclick="attach_event_action(this);"><div class="center">Nao Light Story</div></button><br />
<button class="btn btn-primary btn-large margin large action" data-action="Demo" data-active="false" onclick="attach_event_action(this);"><div class="center">Demo</div></button><br />
</div>
</div>